name: publish to nuget
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: publish EfRest
        id: publish_efrest
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EfRest/EfRest.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: publish EfRest.Swagger
        id: publish_efrest_swagger
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EfRest.Swagger/EfRest.Swagger.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
